
package com.wp.utils.crm;

import org.springframework.stereotype.Service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICustomerService", targetNamespace = "http://service.wp.com/")
@XmlSeeAlso({
})
@Service
public interface ICustomerService {


    /**
     * 
     * @return
     *     returns java.util.List<com.wp.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllNotAssociation", targetNamespace = "http://service.wp.com/", className = "com.wp.service.GetAllNotAssociation")
    @ResponseWrapper(localName = "getAllNotAssociationResponse", targetNamespace = "http://service.wp.com/", className = "com.wp.service.GetAllNotAssociationResponse")
    public List<Customer> getAllNotAssociation();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.wp.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllHasAssociation", targetNamespace = "http://service.wp.com/", className = "com.wp.service.GetAllHasAssociation")
    @ResponseWrapper(localName = "getAllHasAssociationResponse", targetNamespace = "http://service.wp.com/", className = "com.wp.service.GetAllHasAssociationResponse")
    public List<Customer> getAllHasAssociation(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.wp.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://service.wp.com/", className = "com.wp.service.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://service.wp.com/", className = "com.wp.service.GetAllResponse")
    public List<Customer> getAll();

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "saveCustomerAndDecidedZone", targetNamespace = "http://service.wp.com/", className = "com.wp.service.SaveCustomerAndDecidedZone")
    @ResponseWrapper(localName = "saveCustomerAndDecidedZoneResponse", targetNamespace = "http://service.wp.com/", className = "com.wp.service.SaveCustomerAndDecidedZoneResponse")
    public void saveCustomerAndDecidedZone(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    List<Integer> arg1);

}
